name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:

    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Free up some disk space on ubuntu
      if: ${{ runner.os == 'Linux' }}
      run: |
        # Workaround to provide additional free space for testing.
        #   https://github.com/actions/virtual-environments/issues/2840
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
        check-latest: true

    - name: Release Notes
      run: ./resources/scripts/release_notes.sh > ./release_notes.md

    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: latest
        args: release --release-notes=./release_notes.md --timeout 120m
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:

    - name: Check Out Repo
      uses: actions/checkout@v4

    - name: Free up some disk space on ubuntu
      if: ${{ runner.os == 'Linux' }}
      run: |
        # Workaround to provide additional free space for testing.
        #   https://github.com/actions/virtual-environments/issues/2840
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_SM_READONLY_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SM_READONLY_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: get secrets from aws sm
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          ,sdlc/prod/github/dockerhub_token
        parse-json-secrets: true

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: vectorizedbot
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Install Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker meta CGO
      id: docker_meta_cgo
      uses: docker/metadata-action@v5
      with:
        images: |
          redpandadata/connect
        flavor: |
          latest=auto
          suffix=-cgo
        tags: |
          type=semver,suffix=-cgo,pattern={{version}}
          type=semver,suffix=-cgo,pattern={{major}}.{{minor}}
          type=semver,suffix=-cgo,pattern={{major}}

    - name: Build and push CGO
      uses: docker/build-push-action@v6
      with:
        context: ./
        file: ./resources/docker/Dockerfile.cgo
        push: true
        tags: ${{ steps.docker_meta_cgo.outputs.tags }}

    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v5
      with:
        images: |
          redpandadata/connect
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./
        file: ./resources/docker/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}

    - name: Docker meta cloud
      id: docker_meta_cloud
      uses: docker/metadata-action@v5
      with:
        images: |
          redpandadata/connect
        flavor: |
          latest=auto
          suffix=-cloud
        tags: |
          type=semver,suffix=-cloud,pattern={{version}}
          type=semver,suffix=-cloud,pattern={{major}}.{{minor}}
          type=semver,suffix=-cloud,pattern={{major}}

    - name: Build and push cloud
      uses: docker/build-push-action@v6
      with:
        context: ./
        file: ./resources/docker/Dockerfile.cloud
        builder: ${{ steps.buildx.outputs.name }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        tags: ${{ steps.docker_meta_cloud.outputs.tags }}


